name: Validate and merge hostnames when PR approved

on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  add-hosts:
    name: hostnames
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: "./.nvmrc"
    - run: yarn --frozen-lockfile
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: process hosts lists
      run: .github/workflows/process-hostlists.sh

  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs:
      - add-hosts
    steps:
    - run: echo "Great success!"
