name: Sync branch

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    #  legacy master branch is still used by older MetaMask versions. Sync automatically with the current main branch to keep lists in sync.
    name: Sync legacy branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: MetaMask/action-sync-branch@0c8afe60810de1c260ec288bc792b6f513bbcc23
        with:
          branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
